public enum TokenType {
    OP_MULTIPLY, OP_DIVIDE, OP_MOD, OP_ADD, OP_SUBTRACT, OP_LESS, OP_LESSEQUAL, OP_GREATER,
    OP_GREATEREQUAL, OP_EQUAL, OP_NOTEQUAL, OP_ASSIGN, LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE,
    RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET, SEMICOLON, COMMA, KEYWORD_IF, KEYWORD_ELSE,
    KEYWORD_INT, KEYWORD_STRING, KEYWORD_PUBLIC, KEYWORD_CLASS, KEYWORD_VOID, KEYWORD_STATIC,
    IDENTIFIER, INTEGER, STRING, HOBBITS_SAY, HOBBITS_DO}
